# Generated by Django 3.1.7 on 2021-03-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ingredients',
            fields=[
                ('id_ingredient', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tools',
            fields=[
                ('id_tools', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mdp', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=200)),
                ('allergy', models.CharField(max_length=200)),
                ('diet', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('id_recipe', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ingredients_id', models.ManyToManyField(to='api_kale.ingredients')),
                ('tools_id', models.ManyToManyField(to='api_kale.tools')),
            ],
        ),
    ]
